/*
 * This source file was generated by the Gradle 'init' task
 */
package org.micahgruenwald.mandelbrotmultithread;

class AppTest {
  public static void main(String[] args) {
    testSingleMandelbrot();
  }

  public static void testSingleMandelbrot() {
    MandelbrotThread mandelbrot = new MandelbrotThread(-2.0, -1.25, .5, 1.25, 0.01, 0.01);
    mandelbrot.run();
    
  }
}
