/*
 * This source file was generated by the Gradle 'init' task
 */
package org.micahgruenwald.mandelbrotmultithread;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;
















class AppTest {
  public static void main(String[] args) {
    // testSingleMandelbrot();
    testManager();
  }

  public static void testSingleMandelbrot() {
    BufferedImage image = new BufferedImage(101, 101, BufferedImage.TYPE_INT_RGB);
    MandelbrotThread mandelbrot1 =
        new MandelbrotThread(-2.0, -1.25, .5, 1.25, 50, 0, 100,100, image);
    mandelbrot1.start();

    try {
      mandelbrot1.join();
      File outputfile =
          new File(
              "app/src/test/java/org/micahgruenwald/mandelbrotmultithread/testOutput/saved.png");
      ImageIO.write(image, "png", outputfile);
    } catch (IOException e) {
    } catch (InterruptedException e) {
      // TODO Auto-generated catch block
      e.printStackTrace();
    }
  }

  public static void testManager(){
    long ti = System.nanoTime();
        System.out.println("Processors: "+Runtime.getRuntime().availableProcessors());
    BufferedImage image = new BufferedImage(350, 350, BufferedImage.TYPE_INT_RGB);
    Calculator.setColorMode(ColorMode.RANDOM);
    Manager manager = new Manager(8, new RenderArea(-0.10715091471597,- 0.91210539052909, 0.001,0.001), image);

    manager.start();
        try {
          manager.join();
          System.out.println("Runtime: " + (System.nanoTime() - ti) * 1e-9);
      File outputFile =
          new File(
              "app/src/test/java/org/micahgruenwald/mandelbrotmultithread/testOutput/saved.png");
      ImageIO.write(image, "png", outputFile);
    } catch (IOException | InterruptedException e) {
    }
  }
}
